
# -*- coding: utf-8 -*-
"""CustomersSegmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11DDulUFqroUbLkGprwYeg8aHyqr1ZmYZ

# Introduction

This notebook explores customer behavior using an unsupervised learning approach applied to a credit card usage dataset. The data captures a wide range of financial activities, including balances, purchase patterns, cash advances, payment behavior, and credit limits, providing a rich foundation for understanding how customers interact with their accounts. Since no predefined labels or customer categories are available, the goal is to uncover natural structure within the data through clustering. After cleaning, transforming, and standardizing the features, we analyze the underlying patterns to identify meaningful customer segments that support data-driven decision-making and strategic insights.

# Required Libraries
"""
import pip
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, calinski_harabasz_score
from sklearn.decomposition import PCA
from sklearn.cluster import MiniBatchKMeans
from sklearn.cluster import estimate_bandwidth
from sklearn.cluster import DBSCAN
from sklearn.neighbors import NearestNeighbors
from sklearn.mixture import GaussianMixture
from sklearn.cluster import AgglomerativeClustering
from scipy.cluster.hierarchy import dendrogram, linkage
import plotly.express as px

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

data=pd.read_csv(r"C:\Users\91996\Downloads\Rohin\Customer_Data.csv")
df=pd.DataFrame(data)

df.head()

"""| Name    |   describtion | eg   |
|---------|-------|--------|
| CUST_ID  |    identical | C10001,C10002 |
| Balance     |    Balance amount left in the account | 40.900749,3202.467416 |
| Balance_Frequency | How frequently the balance is updated| 0.818,0.909  |
| Purchases| The amount of purchases from the account|95.40,0.00|
| Oneoff_Purchases| Maximum amount of purchases in one time|0.00,773.17|
| Installments_Purchases| The amount of purchases in installments |95.40,0.00|
| Cash_Advance| The cash the user was given in advance| 0.0,6442.95|
| Purchases_Frequency| How frequently the purchases was made (between 0,1)| 0.16,0.0,1.0|
| Oneoff_Purchases_Frequently| How frequently users have one go purchases |0.083,0.0,0.66|
| Purchases_Installments_Frequency| How often the purchases were done in installments|0.0833,0.0,0.66|
| Cash_Advances_Frequency| How frequently the cash paid in advance |0.0,0.25|
| Cash_Advance_TRX| Number of transactions were done in advance by cash|0,4,1,2|
| Purchases_TRX| Number of transactions were made for Purchases|2,0,12,0|
| Credit_Limit| credit card max limitation| 1000.0,7000.0|
| Payments| The amount of payments done by user| 201.80,4103.03|
| Minimum_payments| Minimum amount of payment the user paid| 139.50,627.28|
| PRC_Full_Payment| Percent of full payment| 0.0,0.22, 0.5|
| Tenure| Duration of Credit card service|12,6|
"""

df.info()

df.describe()

# missing values
df.isna().sum()

df[df.CREDIT_LIMIT.isna()]

"""Since there is only one missing value and the number of rows is substantial, we can remove this row from the dataset."""

df[df.MINIMUM_PAYMENTS.isna()]

plt.figure(figsize=(12,7))
sns.heatmap(df.iloc[:, 1:].corr().round(2), annot=True, cmap='Blues')
st.pyplot(plt.figure(figsize=(12, 7)))
plt.close()


"""+ There is no strong correlation between minimum payment and other features, so we can not replace missing values based on different features, and since the number of rows containing missing values is significant, the best way to replace them would be median"""

df1=df.copy()
df1=df1.drop(df1[df1.CREDIT_LIMIT.isna()].index, axis=0)
df1['MINIMUM_PAYMENTS'] = df1['MINIMUM_PAYMENTS'].fillna(df1['MINIMUM_PAYMENTS'].median())

"""# Data Processing & Finding Outliers"""

fig,axes=plt.subplots(9,2, figsize=(10,20))
axes=axes.flatten()
for i,col in enumerate(df1.columns[1:]):
    sns.boxplot(data=df1, x=col, whis=2.5, ax=axes[i])
    axes[i].set_title(f'Distribution of {col}')
for j in range(i+1, len(axes)):
    fig.delaxes(axes[j])
#plt.tight_layout()
fig, axes = plt.subplots(2, 2, constrained_layout=True)
#plt.show()

"""+ At this stage, we do not need to remove any outliers, since the number of outliers is high, but it could be because of the#  concept of the dataset itself.

+ There might be irrational numbers in the data set, for instant we have the summation of purchases, and also installment purchases, and one-off purchases
"""

df1['check']=df1['ONEOFF_PURCHASES']+df1['INSTALLMENTS_PURCHASES']==df1['PURCHASES']
wrong_rows=df1[~df1['check']]
print(wrong_rows)

"""+ 492 rows do not follow the rule, so we can replace these rows with the summation of one-off purchases and installment purchases in the purchases columns."""

df1['PURCHASES']=df1['ONEOFF_PURCHASES']+df1['INSTALLMENTS_PURCHASES']

df1['check']=df1['ONEOFF_PURCHASES']+df1['INSTALLMENTS_PURCHASES']==df1['PURCHASES']
wrong_rows=df1[~df1['check']]
print(wrong_rows)

"""We know if the purchases have been done so the number of transaction can not be 0. Let's check this.

✅
"""

df1[((df1.PURCHASES==0)&(df1.PURCHASES_TRX!=0))|((df1.PURCHASES!=0)&(df1.PURCHASES_TRX==0))]

df2 = df1[
    ~(
        ((df1['PURCHASES'] == 0) & (df1['PURCHASES_TRX'] != 0)) |
        ((df1['PURCHASES'] != 0) & (df1['PURCHASES_TRX'] == 0))
    )
]

"""If the purchases is equal to 0 then perchases frequency has to be 0"""

df2[(df2.PURCHASES==0)&(df2.PURCHASES_FREQUENCY!=0)]

df3=df2[~((df2.PURCHASES==0)&(df2.PURCHASES_FREQUENCY!=0))]

"""If purchases is 0 then the oneoff_purchases also has to be 0"""

df3[(df3.PURCHASES==0)&(df3.ONEOFF_PURCHASES!=0)]

"""If oneoff_purchases is 0, then the oneoff_purchases_frequency also has to be 0."""

df3[(df3.ONEOFF_PURCHASES==0)&(df3.ONEOFF_PURCHASES_FREQUENCY!=0)]

"""If installments_purchases is 0 then purchases_installments_frequency has to be 0"""

var = df3[(df3.INSTALLMENTS_PURCHASES == 0) & (df3.PURCHASES_INSTALLMENTS_FREQUENCY != 0)]

"""If cash advance is 0 then cash advance frequency also has to be 0"""

df3[(df3.CASH_ADVANCE==0)&(df3.CASH_ADVANCE_FREQUENCY!=0)]

"""
✅









If payments is 0 then minimum payments also has to be 0"""

df3[(df3.PAYMENTS==0)&(df3.MINIMUM_PAYMENTS!=0)]

"""❌

In this case, instead of the minimum_payments be 0 it is 312.452292. I assumen we can set these values to 0.
"""

df3.loc[(df3['PAYMENTS'] == 0) & (df3['MINIMUM_PAYMENTS'] != 0), 'MINIMUM_PAYMENTS'] = 0.0

df3[(df3.PAYMENTS==0)&(df3.MINIMUM_PAYMENTS!=0)]

df3[(df3.PAYMENTS==0)&(df3.PRC_FULL_PAYMENT!=0)]

"""✅









Minimum payment has to be lower than the payments
"""

df3[(df3.MINIMUM_PAYMENTS)>(df3.PAYMENTS)]

"""Since there are a lot of rows where the minimum payment is higher than the payments, the rational decision would be to drop the minimum payment column and not remove the rows."""

df4=df3.drop(['MINIMUM_PAYMENTS'],axis=1)

df4.drop('check',axis=1,inplace =True)

df4.describe()

"""# Expelory Data Analysis (EDA)"""

fig,axes=plt.subplots(8,2,figsize=(16,20))
axes=axes.flatten()
for i, col in enumerate (df4.columns[1:]):
    sns.histplot(data=df4,x=col,kde=True, ax=axes[i])
    median=df4[col].median()
    variance=df4[col].var()#
    mean=df4[col].mean()
    axes[i].text(0.75,0.85,f'Variance= {variance:.2f}', transform=axes[i].transAxes)
    axes[i].axvline(median, color='red',linestyle='--', label=f'median: {median:.2f}')
    axes[i].text(0.75,0.75, f'Median= {median:.2f}',transform=axes[i].transAxes)
    axes[i].text(0.75,0.65, f'Mean= {mean:.2f}',transform=axes[i].transAxes)
    axes[i].set_title(f' Distribution of {col}')
#plt.tight_layout()
fig, axes = plt.subplots(2, 2, constrained_layout=True)
#plt.show()

"""+ All data are right-skewed. To have a better model, our preference is to have a normally distributed data set. What we can do is convert all features to logs, and we may have normally distributed data."""

df5=df4.copy()
for col in df5.columns[1:]:
    df5[col]=np.log1p(df5[col])

fig,axes=plt.subplots(8,2,figsize=(16,20))
axes=axes.flatten()
for i, col in enumerate (df5.columns[1:]):
    sns.histplot(data=df5,x=col,kde=True, ax=axes[i])
    median=df5[col].median()
    variance=df5[col].var()#
    mean=df5[col].mean()
    axes[i].text(0.75,0.85,f'Variance= {variance:.2f}', transform=axes[i].transAxes)
    axes[i].axvline(median, color='red',linestyle='--', label=f'median: {median:.2f}')
    axes[i].text(0.75,0.75, f'Median= {median:.2f}',transform=axes[i].transAxes)
    axes[i].text(0.75,0.65, f'Mean= {mean:.2f}',transform=axes[i].transAxes)
    axes[i].set_title(f' Distribution of {col}')
#plt.tight_layout()
fig, axes = plt.subplots(2, 2, constrained_layout=True)
#plt.show()

"""+ The features are not quite well distributed, but they are a bit improved, so we continue with the modified dataset, but only for clustering. For visualisation, we stick to the original dataset."""

counts = df4['TENURE'].value_counts(dropna=False)
labels = counts.index.astype(str)
values = counts.values
colors = sns.color_palette('viridis', len(labels))
color_map = dict(zip(labels, colors))
bar_colors = [color_map[l] for l in labels]

fig, axes = plt.subplots(1, 2, figsize=(14, 6))
axes[0].bar(labels, values, color=bar_colors)
axes[0].set_title('Count of Each Category in TENURE')
axes[0].set_ylabel('Count')
axes[0].set_xlabel('Category')
# Count labels
for i, v in enumerate(values):
    axes[0].text(i, v + max(values) * 0.02, str(v),
                 ha='center', va='bottom', fontsize=10)

axes[1].pie(
    values,
    labels=labels,
    colors=bar_colors,
    startangle=90,
    autopct='%1.1f%%',
    pctdistance=1.1,
    labeldistance=0.8,
    textprops={'fontsize': 10}
)
axes[1].set_title('Percentage Distribution of TENURE')

#plt.tight_layout()
fig, axes = plt.subplots(2, 2, constrained_layout=True)
#plt.show()

# Scatter plot: Balance vs Cash Advance
plt.figure(figsize=(8,6))
sns.scatterplot(data=df4, x='BALANCE', y='CASH_ADVANCE', alpha=0.5)
plt.title('Balance vs Cash Advance')
plt.xlabel('Balance')
plt.ylabel('Cash Advance')
#plt.show()
plt.close()
# Pie chart: Cash Advance categories
bins = [0, 1000, 5000, 10000, df4['CASH_ADVANCE'].max()]
labels = ['No/Low', 'Moderate', 'High', 'Very High']
df4['CashAdvanceCategory'] = pd.cut(df4['CASH_ADVANCE'], bins=bins, labels=labels)
counts = df4['CashAdvanceCategory'].value_counts()
plt.figure(figsize=(6,6))
plt.pie(counts, labels=counts.index, autopct='%1.1f%%', startangle=90,
        colors=sns.color_palette('viridis', len(counts)))
plt.title('Cash Advance Categories')
#plt.show()
plt.close()

"""Only 1,8% pay cash in high amounts and 46% pay cash in moderate and there is some negative correlation between cash advance and balance. Meaning that they pay cash, the account balance after purchase also be more."""

plt.figure(figsize=(8,6))
sns.scatterplot(data=df4, x='ONEOFF_PURCHASES', y='PURCHASES', alpha=0.5)
plt.title('ONEOFF_PURCHASES vs PURCHASES')
plt.xlabel('ONEOFF_PURCHASES')
plt.ylabel('PURCHASES')
#plt.show()
plt.close()

"""# Modelling

To keep the workflow efficient and the notebook lightweight, the modelling section focuses on K‑Means clustering as the primary algorithm for customer segmentation. K‑Means is well‑suited for high‑dimensional numerical data and provides a clear, interpretable structure for identifying distinct groups within the customer base. After evaluating different values of k using metrics such as inertia, silhouette score, and the Calinski–Harabasz index, the final model is selected based on its ability to produce compact, well‑separated clusters. This streamlined approach ensures a balance between computational efficiency and analytical depth, allowing us to derive meaningful insights without unnecessary overhead.
"""

df5=df5.drop('CUST_ID', axis=1)
scaler = StandardScaler().fit(df5)
df_trans = scaler.transform(df5)
df_trans = pd.DataFrame(df_trans, columns = df5.columns)


# Build final model
kmeans_final = KMeans(n_clusters=3, init="random", n_init=10, max_iter=300, random_state=42)
labels = kmeans_final.fit_predict(df_trans)
# Add cluster labels back to your original dataframe for analysis
df6=df5.copy()
df6["Cluster"] = labels



from kneed import KneeLocator   #elbow
k_values = range(2, 11)

inertias = []
silhouette_scores = []
calinski_scores = []
for k in k_values:
    kmeans = KMeans(n_clusters=k, init="random", n_init=10, max_iter=300, random_state=42)
    labels = kmeans.fit_predict(df_trans)
    inertias.append(kmeans.inertia_)
    silhouette_scores.append(silhouette_score(df_trans, labels))
    calinski_scores.append(calinski_harabasz_score(df_trans, labels))

# Detect elbow
knee = KneeLocator(k_values, inertias, curve="convex", direction="decreasing")
elbow_k = knee.knee
print(f"Elbow detected at k={elbow_k}")

# Results table
results_df = pd.DataFrame({
    "k": list(k_values),
    "Inertia": inertias,
    "Silhouette": silhouette_scores,
    "Calinski-Harabasz": calinski_scores
})
print(results_df)

# Find best k by metrics
best_silhouette_k = results_df.loc[results_df["Silhouette"].idxmax(), "k"]
best_calinski_k = results_df.loc[results_df["Calinski-Harabasz"].idxmax(), "k"]


plt.figure(figsize=(18,5))
plt.close()
# Elbow plot
plt.subplot(1,3,1)
plt.plot(k_values, inertias, marker='o')
plt.axvline(x=elbow_k, color='red', linestyle='--', label=f"Elbow k={elbow_k}")
plt.title("Elbow Method (Inertia)")
plt.xlabel("Number of clusters (k)")
plt.ylabel("Inertia")
plt.legend()
plt.close()

# Silhouette plot
plt.subplot(1,3,2)
plt.plot(k_values, silhouette_scores, marker='o')
plt.scatter(best_silhouette_k, max(silhouette_scores), color='red', s=100, label=f"Best k={best_silhouette_k}")
plt.title("Silhouette Score")
plt.xlabel("Number of clusters (k)")
plt.ylabel("Score")
plt.legend()
plt.close()

# Calinski plot
plt.subplot(1,3,3)
plt.plot(k_values, calinski_scores, marker='o')
plt.scatter(best_calinski_k, max(calinski_scores), color='red', s=100, label=f"Best k={best_calinski_k}")
plt.title("Calinski–Harabasz Index")
plt.xlabel("Number of clusters (k)")
plt.ylabel("Score (higher is better)")
plt.legend()

#plt.tight_layout()
fig, axes = plt.subplots(2, 2, constrained_layout=True)
#plt.show()
plt.close()
"""**Based on the score and visualization, the best number of clusters for inertia is 5; the Silhouette score suggests 2 and 7, and the Calinski-Harabasz score suggests 2 or 3. Since we prefer to decrease the number of clusters and also look at the elbow, we also observe a bend in k=3, so we decide to have a model based on 3 clusters.**"""

counts = df6['Cluster'].value_counts(dropna=False)
labels = counts.index.astype(str)
values = counts.values
colors = sns.color_palette('viridis', len(labels))
color_map = dict(zip(labels, colors))
bar_colors = [color_map[l] for l in labels]

fig, axes = plt.subplots(1, 2, figsize=(14, 6))
axes[0].bar(labels, values, color=bar_colors)
axes[0].set_title('Count of Each Cluster')
axes[0].set_ylabel('Count')
axes[0].set_xlabel('Category')
# Count labels
for i, v in enumerate(values):
    axes[0].text(i, v + max(values) * 0.02, str(v),
                 ha='center', va='bottom', fontsize=10)

axes[1].pie(
    values,
    labels=labels,
    colors=bar_colors,
    startangle=90,
    autopct='%1.1f%%',
    pctdistance=1.1,
    labeldistance=0.8,
    textprops={'fontsize': 10}
)
axes[1].set_title('Percentage Distribution of Cluster')

#plt.tight_layout()
fig, axes = plt.subplots(2, 2, constrained_layout=True)
#plt.show()
plt.close()
kmeans_final = KMeans(n_clusters=3, init="random", n_init=10, max_iter=300, random_state=42)
labels = kmeans_final.fit_predict(df_trans)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(df_trans.to_numpy())
plt.figure(figsize=(8,6))
plt.scatter(X_pca[:,0], X_pca[:,1], c=labels, cmap='viridis', s=50)
centers_pca = pca.transform(kmeans_final.cluster_centers_)
plt.scatter(centers_pca[:,0], centers_pca[:,1],
            marker='*', color='red', s=200, label="Centroids")
plt.title("KMeans Clusters (k=3) - PCA projection")
plt.xlabel("PCA 1")
plt.ylabel("PCA 2")
#plt.show()
plt.close()
sns.scatterplot(data=df6, x='CASH_ADVANCE',y='PURCHASES',palette='viridis', hue='Cluster')
#plt.show()

plt.figure(figsize=(6,4))
sns.scatterplot(data=df6, x="BALANCE", y="PURCHASES", hue="Cluster", palette="viridis", s=60)
plt.title("Clusters based on BALANCE vs PURCHASES")
plt.xlabel("BALANCE")
plt.ylabel("PURCHASES")
plt.legend(title="Cluster")
plt.close()
#plt.show()
#
plt.figure(figsize=(6,4))
sns.scatterplot(data=df6, x="CASH_ADVANCE", y="PAYMENTS", hue="Cluster", palette="viridis", s=60)
plt.title("Clusters based on CASH_ADVANCE vs PAYMENTS")
plt.xlabel("CASH_ADVANCE")
plt.ylabel("PAYMENTS")
plt.legend(title="Cluster")
#plt.show()
plt.close()
features = [
    "BALANCE","BALANCE_FREQUENCY","PURCHASES","ONEOFF_PURCHASES","INSTALLMENTS_PURCHASES",
    "CASH_ADVANCE","PURCHASES_FREQUENCY","ONEOFF_PURCHASES_FREQUENCY","PURCHASES_INSTALLMENTS_FREQUENCY",
    "CASH_ADVANCE_FREQUENCY","CASH_ADVANCE_TRX","PURCHASES_TRX","CREDIT_LIMIT",
    "PAYMENTS","PRC_FULL_PAYMENT","TENURE"
]

# Loop through features and plot KDE for each
max_plots = 5  # limit

for i, col in enumerate(features):
    if i >= max_plots:
        break

    plt.figure(figsize=(6,4))
    sns.kdeplot(data=df6, x=col, hue="Cluster", fill=True, common_norm=False, alpha=0.4)
    plt.title(f"Distribution of {col} by Cluster")
    plt.xlabel(col)
    plt.ylabel("Density")
    st.pyplot(plt)

features

# saving the model
from joblib import dump
pickle_out = open("C:\\Users\91996\Downloads\Rohin\CustomerSegmentation.pkl", mode = "wb")
dump(kmeans_final, pickle_out)
pickle_out.close()

print("Model saved as pickle file named -> CustomerSegmentation.pkl ")